name: Setup
description: Perform standard setup and install dependencies using pnpm.

runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 20
    - name: Install dependencies
      shell: bash
      run: pnpm install
