import officer from "@assets/board/boardimage.png";

const boardInfo = [
  {
    section: "Executive Board",
    members: [
      {
        name: "Vincent Lin",
        role: "President",
        image: officer,
        major: "3rd Year Computer Engineering",
        contact: "ufsase.p@gmail.com",
        description: "description",
      },
      {
        name: "Bryan Park",
        role: "Internal Vice President (IVP)",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Kayleen Diaz",
        role: "External Vice President (EVP)",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Gayatri Baskaran",
        role: "Treasurer",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Rachel Young",
        role: "Secretary",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Kimmy Chu",
        role: "Public Relations",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
    ],
  },
  {
    section: "Chair Board",
    members: [
      {
        name: "Ricky Zhang",
        role: "Webmaster",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Amanda Jiang",
        role: "Advancement",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Chloe Bai",
        role: "Fundraising",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Anna Lim",
        role: "Member Involvement",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Justin Doan",
        role: "Member Involvement",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Helen Zou",
        role: "Historian",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Adriel Poon",
        role: "Multimedia",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Reyna Simpson",
        role: "Multimedia",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Tabitha Gottipati",
        role: "Network",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Aahan Dwivedi",
        role: "Science",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Leann Tang",
        role: "Service",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Sophia Dong",
        role: "Social",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Jessica Lu",
        role: "Sports Coordinator",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Alexander Lou",
        role: "Sports Coordinator",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Manav Sanghvi",
        role: "Technical",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
      {
        name: "Kevin Tang",
        role: "Technical",
        image: officer,
        major: "major",
        contact: "contact",
        description: "description",
      },
    ],
  },
];

export default boardInfo;