/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebdevImport } from './routes/webdev'
import { Route as UserpageImport } from './routes/userpage'
import { Route as SportsImport } from './routes/sports'
import { Route as SponsorsImport } from './routes/sponsors'
import { Route as SignupImport } from './routes/signup'
import { Route as SetImport } from './routes/set'
import { Route as SearchImport } from './routes/search'
import { Route as ResourcesImport } from './routes/resources'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ProgramsImport } from './routes/programs'
import { Route as ProfileOLDImport } from './routes/profileOLD'
import { Route as MentorMenteeImport } from './routes/mentor-mentee'
import { Route as LoginImport } from './routes/login'
import { Route as InternsImport } from './routes/interns'
import { Route as GalleryImport } from './routes/gallery'
import { Route as EventsImport } from './routes/events'
import { Route as EmailVerificationImport } from './routes/email-verification'
import { Route as BoardImport } from './routes/board'
import { Route as BlogsImport } from './routes/blogs'
import { Route as AuthedImport } from './routes/authed'
import { Route as AboutImport } from './routes/about'
import { Route as ProfileRouteImport } from './routes/profile/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as ProfileSettingsImport } from './routes/profile/settings'
import { Route as ProfileSecurityImport } from './routes/profile/security'
import { Route as ProfileInfoImport } from './routes/profile/info'

// Create/Update Routes

const WebdevRoute = WebdevImport.update({
  id: '/webdev',
  path: '/webdev',
  getParentRoute: () => rootRoute,
} as any)

const UserpageRoute = UserpageImport.update({
  id: '/userpage',
  path: '/userpage',
  getParentRoute: () => rootRoute,
} as any)

const SportsRoute = SportsImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRoute,
} as any)

const SponsorsRoute = SponsorsImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SetRoute = SetImport.update({
  id: '/set',
  path: '/set',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesRoute = ResourcesImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ProgramsRoute = ProgramsImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRoute,
} as any)

const ProfileOLDRoute = ProfileOLDImport.update({
  id: '/profileOLD',
  path: '/profileOLD',
  getParentRoute: () => rootRoute,
} as any)

const MentorMenteeRoute = MentorMenteeImport.update({
  id: '/mentor-mentee',
  path: '/mentor-mentee',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InternsRoute = InternsImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => rootRoute,
} as any)

const GalleryRoute = GalleryImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoute = EventsImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRoute,
} as any)

const EmailVerificationRoute = EmailVerificationImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => rootRoute,
} as any)

const BoardRoute = BoardImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRoute,
} as any)

const BlogsRoute = BlogsImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/authed',
  path: '/authed',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRouteRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRouteRoute,
} as any)

const ProfileSecurityRoute = ProfileSecurityImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProfileRouteRoute,
} as any)

const ProfileInfoRoute = ProfileInfoImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ProfileRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/authed': {
      id: '/authed'
      path: '/authed'
      fullPath: '/authed'
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsImport
      parentRoute: typeof rootRoute
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardImport
      parentRoute: typeof rootRoute
    }
    '/email-verification': {
      id: '/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof EmailVerificationImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsImport
      parentRoute: typeof rootRoute
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryImport
      parentRoute: typeof rootRoute
    }
    '/interns': {
      id: '/interns'
      path: '/interns'
      fullPath: '/interns'
      preLoaderRoute: typeof InternsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/mentor-mentee': {
      id: '/mentor-mentee'
      path: '/mentor-mentee'
      fullPath: '/mentor-mentee'
      preLoaderRoute: typeof MentorMenteeImport
      parentRoute: typeof rootRoute
    }
    '/profileOLD': {
      id: '/profileOLD'
      path: '/profileOLD'
      fullPath: '/profileOLD'
      preLoaderRoute: typeof ProfileOLDImport
      parentRoute: typeof rootRoute
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/set': {
      id: '/set'
      path: '/set'
      fullPath: '/set'
      preLoaderRoute: typeof SetImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsImport
      parentRoute: typeof rootRoute
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsImport
      parentRoute: typeof rootRoute
    }
    '/userpage': {
      id: '/userpage'
      path: '/userpage'
      fullPath: '/userpage'
      preLoaderRoute: typeof UserpageImport
      parentRoute: typeof rootRoute
    }
    '/webdev': {
      id: '/webdev'
      path: '/webdev'
      fullPath: '/webdev'
      preLoaderRoute: typeof WebdevImport
      parentRoute: typeof rootRoute
    }
    '/profile/info': {
      id: '/profile/info'
      path: '/info'
      fullPath: '/profile/info'
      preLoaderRoute: typeof ProfileInfoImport
      parentRoute: typeof ProfileRouteImport
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityImport
      parentRoute: typeof ProfileRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof ProfileRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof ProfileRouteImport
    }
  }
}

// Create and export the route tree

interface ProfileRouteRouteChildren {
  ProfileInfoRoute: typeof ProfileInfoRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileInfoRoute: ProfileInfoRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/authed': typeof AuthedRoute
  '/blogs': typeof BlogsRoute
  '/board': typeof BoardRoute
  '/email-verification': typeof EmailVerificationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/interns': typeof InternsRoute
  '/login': typeof LoginRoute
  '/mentor-mentee': typeof MentorMenteeRoute
  '/profileOLD': typeof ProfileOLDRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/set': typeof SetRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/sports': typeof SportsRoute
  '/userpage': typeof UserpageRoute
  '/webdev': typeof WebdevRoute
  '/profile/info': typeof ProfileInfoRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authed': typeof AuthedRoute
  '/blogs': typeof BlogsRoute
  '/board': typeof BoardRoute
  '/email-verification': typeof EmailVerificationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/interns': typeof InternsRoute
  '/login': typeof LoginRoute
  '/mentor-mentee': typeof MentorMenteeRoute
  '/profileOLD': typeof ProfileOLDRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/set': typeof SetRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/sports': typeof SportsRoute
  '/userpage': typeof UserpageRoute
  '/webdev': typeof WebdevRoute
  '/profile/info': typeof ProfileInfoRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/authed': typeof AuthedRoute
  '/blogs': typeof BlogsRoute
  '/board': typeof BoardRoute
  '/email-verification': typeof EmailVerificationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/interns': typeof InternsRoute
  '/login': typeof LoginRoute
  '/mentor-mentee': typeof MentorMenteeRoute
  '/profileOLD': typeof ProfileOLDRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/set': typeof SetRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/sports': typeof SportsRoute
  '/userpage': typeof UserpageRoute
  '/webdev': typeof WebdevRoute
  '/profile/info': typeof ProfileInfoRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/about'
    | '/authed'
    | '/blogs'
    | '/board'
    | '/email-verification'
    | '/events'
    | '/gallery'
    | '/interns'
    | '/login'
    | '/mentor-mentee'
    | '/profileOLD'
    | '/programs'
    | '/reset-password'
    | '/resources'
    | '/search'
    | '/set'
    | '/signup'
    | '/sponsors'
    | '/sports'
    | '/userpage'
    | '/webdev'
    | '/profile/info'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authed'
    | '/blogs'
    | '/board'
    | '/email-verification'
    | '/events'
    | '/gallery'
    | '/interns'
    | '/login'
    | '/mentor-mentee'
    | '/profileOLD'
    | '/programs'
    | '/reset-password'
    | '/resources'
    | '/search'
    | '/set'
    | '/signup'
    | '/sponsors'
    | '/sports'
    | '/userpage'
    | '/webdev'
    | '/profile/info'
    | '/profile/security'
    | '/profile/settings'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/about'
    | '/authed'
    | '/blogs'
    | '/board'
    | '/email-verification'
    | '/events'
    | '/gallery'
    | '/interns'
    | '/login'
    | '/mentor-mentee'
    | '/profileOLD'
    | '/programs'
    | '/reset-password'
    | '/resources'
    | '/search'
    | '/set'
    | '/signup'
    | '/sponsors'
    | '/sports'
    | '/userpage'
    | '/webdev'
    | '/profile/info'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthedRoute: typeof AuthedRoute
  BlogsRoute: typeof BlogsRoute
  BoardRoute: typeof BoardRoute
  EmailVerificationRoute: typeof EmailVerificationRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  InternsRoute: typeof InternsRoute
  LoginRoute: typeof LoginRoute
  MentorMenteeRoute: typeof MentorMenteeRoute
  ProfileOLDRoute: typeof ProfileOLDRoute
  ProgramsRoute: typeof ProgramsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SetRoute: typeof SetRoute
  SignupRoute: typeof SignupRoute
  SponsorsRoute: typeof SponsorsRoute
  SportsRoute: typeof SportsRoute
  UserpageRoute: typeof UserpageRoute
  WebdevRoute: typeof WebdevRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthedRoute: AuthedRoute,
  BlogsRoute: BlogsRoute,
  BoardRoute: BoardRoute,
  EmailVerificationRoute: EmailVerificationRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  InternsRoute: InternsRoute,
  LoginRoute: LoginRoute,
  MentorMenteeRoute: MentorMenteeRoute,
  ProfileOLDRoute: ProfileOLDRoute,
  ProgramsRoute: ProgramsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SetRoute: SetRoute,
  SignupRoute: SignupRoute,
  SponsorsRoute: SponsorsRoute,
  SportsRoute: SportsRoute,
  UserpageRoute: UserpageRoute,
  WebdevRoute: WebdevRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/about",
        "/authed",
        "/blogs",
        "/board",
        "/email-verification",
        "/events",
        "/gallery",
        "/interns",
        "/login",
        "/mentor-mentee",
        "/profileOLD",
        "/programs",
        "/reset-password",
        "/resources",
        "/search",
        "/set",
        "/signup",
        "/sponsors",
        "/sports",
        "/userpage",
        "/webdev"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile/route.tsx",
      "children": [
        "/profile/info",
        "/profile/security",
        "/profile/settings",
        "/profile/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/authed": {
      "filePath": "authed.tsx"
    },
    "/blogs": {
      "filePath": "blogs.tsx"
    },
    "/board": {
      "filePath": "board.tsx"
    },
    "/email-verification": {
      "filePath": "email-verification.tsx"
    },
    "/events": {
      "filePath": "events.tsx"
    },
    "/gallery": {
      "filePath": "gallery.tsx"
    },
    "/interns": {
      "filePath": "interns.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/mentor-mentee": {
      "filePath": "mentor-mentee.tsx"
    },
    "/profileOLD": {
      "filePath": "profileOLD.tsx"
    },
    "/programs": {
      "filePath": "programs.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/resources": {
      "filePath": "resources.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/set": {
      "filePath": "set.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/sponsors": {
      "filePath": "sponsors.tsx"
    },
    "/sports": {
      "filePath": "sports.tsx"
    },
    "/userpage": {
      "filePath": "userpage.tsx"
    },
    "/webdev": {
      "filePath": "webdev.tsx"
    },
    "/profile/info": {
      "filePath": "profile/info.tsx",
      "parent": "/profile"
    },
    "/profile/security": {
      "filePath": "profile/security.tsx",
      "parent": "/profile"
    },
    "/profile/settings": {
      "filePath": "profile/settings.tsx",
      "parent": "/profile"
    },
    "/profile/": {
      "filePath": "profile/index.tsx",
      "parent": "/profile"
    }
  }
}
ROUTE_MANIFEST_END */
